### ISSUE TITLE
Problem while running the app.py file

### ISSUE THREAD

**Issue by mubeenpatel99** [shibli2700/aadhaarcrypt#2]
When we run the app.py file it shows an error saying "No module names Crypto".
![Error](https://user-images.githubusercontent.com/42268754/55819388-449c1a80-5b16-11e9-87ea-96aca1e24750.JPG)

**Comment by d1089** [comment]
first make sure you have executed the `python setup.py install` command

**Comment by mubeenpatel99** [comment]
Tried that, the setup is installing all the dependencies l, checked the list of dependencies installed everything is present but still the program cannot find the Crypto module

**Comment by d1089** [comment]
Check `PATH` variable inside environment variables properly `SET` or not

**Comment by mubeenpatel99** [comment]
Checked the path too, other programs running well!

**Comment by shibli2700** [comment]
Thank you @mubeenpatel99 for pointing out the issue, I have fixed the issue in the main repository.
Windows users need to install **pycryptodome**.

```
pip install pycryptodome
```

I have added **pycryptodome** as a dependency in the repository.

Thank you.

**Comment by mubeenpatel99** [comment]
Thank you @shibli2700 for looking into the issue, the problem is resolved and the program is working great.
Keep Contributing.👨‍💻
We need more of these!🐱‍🏍
